### PR TITLE
Fix layer opacity bug

### PR DESCRIPTION
**Pull request by stdavis**
This was originally discovered in this issue: https://github.com/agrc/wfrc-wasatch-choice/issues/256

### CODE REVIEW

**Comment by steveoh** [comment]
If I remember correctly, this is one opacity slider to affect every layer in the map. If the client has a map with layers with non default opacity set and they interact with the slider, aren't the opacity properties all going to be set to the value of the slider? This would never allow the initial state of the layers to be reached again. Am I understanding the issue correctly?

**Comment by stdavis** [comment]
Yes, the slider affects every layer that is associated with the layer selector in the map. I didn't think that it wouldn't be useful to have all of the layers be reset to the same opacity if the initial value for one is different. So I made the opacity slider affect the relative opacity. If the initial opacity for a layer is `0.5` and the user slides the opacity slide halfway down, then the layer's opacity would be changed to `0.25`. If there is another layer with an initial opacity set to `1`, it would be changed to `0.5`.

**Comment by steveoh** [comment]
That's pretty nice. So if a layer has an initial of .5 and another has 1, if you take the slider to 50% the .5 is now hidden and the 1 is at .5. Then if you take it down to 0% they are both hidden. To bring them both back you have to go back above 50%? It looks like you kept the original value to be able to do that right?

**Comment by stdavis** [comment]
That's not quite right. The opacity slider just sets the layer's new opacity as a percentage of it's original opacity. Suppose you have layer "a" with a config opacity of 1 and layer "b" with a config opacity of 0.5. If you move the slider down to 1/2, then layer "a" opacity would be set to 0.5 and layer "b" would be set to 0.25.

**Comment by stdavis** [comment]
That's not quite right. The opacity slider acts as a percentage of the original config value. Suppose you have layer "a" with a config opacity of 1 and layer "b" with a config opacity of 0.5. If you move the slider down to 1/2, then layer "a" opacity would be set to 0.5 and layer "b" would be set to 0.25.

**Comment by steveoh** [comment]
chatting offline, scott decided he liked a subtract vs multiply solution since the visibility ratio between layers is kept.

**Review by steveoh — APPROVED** [review]

**Pull request merged**
